name: Keep Andina Trading Awake

on:
  schedule:
    # Lunes a Viernes: 8:00 AM - 4:59 PM (Hora Colombia)
    - cron: '*/8 13-21 * * 1-5'
  
  workflow_dispatch:

jobs:
  ping-andina:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Andina Trading
        # IMPORTANTE: Reemplaza esta URL por el subdominio real de tu proyecto en Render
        run: curl -f -I -m 10 https://TU-URL-DE-ANDINA.onrender.com/ping
