name: Keep Render Apps Awake

on:
  schedule:
    # 1. Lunes a Viernes de 8:00 AM a 6:59 PM (Hora Colombia)
    # Equivale a 13:00 - 23:59 en UTC (días 1 al 5)
    - cron: '*/14 13-23 * * 1-5'
    
    # 2. Lunes a Viernes de 7:00 PM a 8:00 PM (Hora Colombia)
    # Equivale a 00:00 - 00:59 en UTC DEL DÍA SIGUIENTE (Martes a Sábado, días 2 al 6)
    - cron: '*/14 0 * * 2-6'
    
    # 3. Sábados de 8:00 AM a 3:59 PM (Hora Colombia)
    # Equivale a 13:00 - 20:59 en UTC (día 6)
    - cron: '*/14 13-20 * * 6'
  
  # Botón manual para pruebas
  workflow_dispatch:

jobs:
  ping-services:
    runs-on: ubuntu-latest
    steps:
      - name: Ping AstroURL
        run: curl -s https://astrourls.onrender.com/ping
        
      - name: Ping Proyecto 2
        # Reemplaza la URL de abajo con la de tu otro proyecto
        run: curl -s https://andina-trading-portfolio.onrender.com/ping
